from pydantic import BaseModel
from typing import Optional
from typing import List

class Source(BaseModel):
    id: Optional[str] = None  # UUID or autogenerated
    publisher: str
    headline: str
    url: str
    summary: str = "No summary available"
    is_trusted: Optional[bool] = False
    date_published: Optional[str] = None
    
class Sources(BaseModel):
    sources: List[Source]


