from pydantic import BaseModel
from typing import Optional

class Source(BaseModel):
    id: Optional[str] = None  # UUID or autogenerated
    publisher: str
    headline: str
    url: str
    summary: Optional[str] = None
    is_curated: Optional[bool] = False

class FindSourcesRequest(BaseModel):
    project_id: str
    search_prompt: str

class AddToLibraryRequest(BaseModel):
    source_id: str

class RemoveFromLibraryRequest(BaseModel):
    source_id: str